# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0oGspjMoHy1pjnkfzimre5txaZ03430
"""

def time_for_func(func_):
  import time
  
  def wrapper():
        start = time.time()
        func_()
        end = time.time()
        print("Час виконання: {0} секунд.".format(end-start))
  return wrapper

@time_for_func
def aver_list():
  list_1 = []
  while True: 
       n = int(input())
       list_1.append(n) 
       if n == 0: 
            break
  print(sum(list_1)/len(list_1))

aver_list()

import time


def time_aver_list(func_):
    def wrapper():
        time_1 = time.time()
        func_()
        time_2 = time.time()
        print("Функція працювала {0} секунд".format(time_2 - time_1))
    return wrapper


@time_aver_list
def aver_list():
    list_1 = []
    while True:
        if number == 0:
            break
        list_1.append(number)
    average = sum(list_1) / len(list_1)
    print("Середнє арифметичне введених Вами чисел дорівнює: ", average)


aver_list()





